# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.poc-network.com:
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    container_name: orderer.poc-network.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/poc-network.com/orderers/orderer.poc-network.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/poc-network.com/orderers/orderer.poc-network.com/tls/:/var/hyperledger/orderer/tls
        - orderer.poc-network.com:/var/hyperledger/production/orderer
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    ports:
      - 7050:7050

  peer0.parents.poc-network.com:
    container_name: peer0.parents.poc-network.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_byfn
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.parents.poc-network.com
      - CORE_PEER_ADDRESS=peer0.parents.poc-network.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.parents.poc-network.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.parents.poc-network.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.parents.poc-network.com:7051
      - CORE_PEER_LOCALMSPID=ParentsMSP
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/parents.poc-network.com/peers/peer0.parents.poc-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/parents.poc-network.com/peers/peer0.parents.poc-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.parents.poc-network.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.parents.poc-network.com:
    container_name: peer1.parents.poc-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.parents.poc-network.com
      - CORE_PEER_ADDRESS=peer1.parents.poc-network.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.parents.poc-network.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.parents.poc-network.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.parents.poc-network.com:7051
      - CORE_PEER_LOCALMSPID=ParentsMSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_byfn
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/parents.poc-network.com/peers/peer1.parents.poc-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/parents.poc-network.com/peers/peer1.parents.poc-network.com/tls:/etc/hyperledger/fabric/tls
        - peer1.parents.poc-network.com:/var/hyperledger/production
    image: hyperledger/fabric-peer:$IMAGE_TAG
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start

    ports:
      - 8051:8051

  peer0.hospital.poc-network.com:
    container_name: peer0.hospital.poc-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.hospital.poc-network.com
      - CORE_PEER_ADDRESS=peer0.hospital.poc-network.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.hospital.poc-network.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.hospital.poc-network.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.hospital.poc-network.com:10051
      - CORE_PEER_LOCALMSPID=HospitalMSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_byfn
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/hospital.poc-network.com/peers/peer0.hospital.poc-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/hospital.poc-network.com/peers/peer0.hospital.poc-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.hospital.poc-network.com:/var/hyperledger/production
    image: hyperledger/fabric-peer:$IMAGE_TAG
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 9051:9051


  peer1.hospital.poc-network.com:
    container_name: peer1.hospital.poc-network.com
    environment:
      - CORE_PEER_ID=peer1.hospital.poc-network.com
      - CORE_PEER_ADDRESS=peer1.hospital.poc-network.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.hospital.poc-network.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.hospital.poc-network.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.hospital.poc-network.com:9051
      - CORE_PEER_LOCALMSPID=HospitalMSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_byfn
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/hospital.poc-network.com/peers/peer1.hospital.poc-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/hospital.poc-network.com/peers/peer1.hospital.poc-network.com/tls:/etc/hyperledger/fabric/tls
        - peer1.hospital.poc-network.com:/var/hyperledger/production
    ports:
      - 10051:10051
    image: hyperledger/fabric-peer:$IMAGE_TAG
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start


  peer0.kindergarten.poc-network.com:
    container_name: peer0.kindergarten.poc-network.com
    environment:
      - CORE_PEER_ID=peer0.kindergarten.poc-network.com
      - CORE_PEER_ADDRESS=peer0.kindergarten.poc-network.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.kindergarten.poc-network.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.kindergarten.poc-network.com:12051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.kindergarten.poc-network.com:11051
      - CORE_PEER_LOCALMSPID=KindergartenMSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_byfn
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/kindergarten.poc-network.com/peers/peer0.kindergarten.poc-network.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/kindergarten.poc-network.com/peers/peer0.kindergarten.poc-network.com/tls:/etc/hyperledger/fabric/tls
      - peer0.kindergarten.poc-network.com:/var/hyperledger/production
    ports:
      - 11051:11051
    networks:
      - byfn
    image: hyperledger/fabric-peer:$IMAGE_TAG
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start

  peer1.kindergarten.poc-network.com:
    container_name: peer1.kindergarten.poc-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.kindergarten.poc-network.com
      - CORE_PEER_ADDRESS=peer1.kindergarten.poc-network.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer1.kindergarten.poc-network.com:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.kindergarten.poc-network.com:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.kindergarten.poc-network.com:12051
      - CORE_PEER_LOCALMSPID=KindergartenMSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_byfn
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/kindergarten.poc-network.com/peers/peer1.kindergarten.poc-network.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/kindergarten.poc-network.com/peers/peer1.kindergarten.poc-network.com/tls:/etc/hyperledger/fabric/tls
      - peer1.kindergarten.poc-network.com:/var/hyperledger/production
    ports:
      - 12051:12051
    networks:
      - byfn
    image: hyperledger/fabric-peer:$IMAGE_TAG
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
